### PR TITLE
Dev branch + Karen/Sofia plotting script

### PR DESCRIPTION
**Pull request by telegraphic**

### CODE REVIEW

**Comment by texadactyl** [comment]
When I removed line 377 (the end) of plot_event.py and re-installed turbo_seti-dev, then command line turboSETI and importing FinDopp in a Python 3 script work fine:
```
"""
Turbo Seti FinDoppler Test
"""
from os import getenv
from turbo_seti.findoppler.findopp import FinDoppler
HOME = getenv("HOME")
DATADIR = HOME + "/data/voyager/"
DATAFILE = DATADIR + "Voyager1.single_coarse.fine_res.h5"
print("Calling FinDoppler({})".format(DATAFILE))
print("Output directory: {}".format(DATADIR))
FD = FinDoppler(DATAFILE, 2, out_dir=DATADIR)
FD.search()

```
Perhaps, line 377 belongs in part of a test program along with the referenced files for the plot_event functions.

**Comment by texadactyl** [comment]
If you really want to leave line 377 there because everyone is too busy to create a plot_event.py test program, then I suggest amending that line as follows:
```
if __name__ == "__main__":
    plot_candidate_events_individually('B04_f2_snr20.csv', 'B01_B04_fil.lst', 'B04', 'blc00', 2, show=True, overwrite=False, offset=0)
```

**Comment by telegraphic** [comment]
@texadactyl right you are, that debugging line 377 shouldn't be there long term. Will still be a while until the dev branch is merged as Sofia and Karen are still working on their changes (I pre-issued this PR as it is useful for tracking progress).

**Comment by texadactyl** [comment]
Just put the 
if __name__ == "__main__":
in front of it and the problem is solved.

**Comment by telegraphic** [comment]
I got carried away and made quite a few changes -- far past the L377 issue, with the goal of getting codecov running. Will touch base with other authors about how to test with the new changes.

**Comment by texadactyl** [comment]
@telegraphic 
I get carried away all the time.

**Comment by telegraphic** [comment]
Hooray! Code coverage works.

**Comment by telegraphic** [comment]
Ok I'm going to merge this branch, as KB in slack channel showed that channel flip issue is coming up in master, so master branch is broken. Unit tests will be important going forward too!

**Pull request merged**
