### PR TITLE
Issues #59 & 62 + fix some (not all) pylint remarks + tidy up

### PR DESCRIPTION
**Pull request by texadactyl**
Pylint fixes:
* Removed imports and calculations which were not used.
* Reordered imports of packages as follows: (a) system packages, (b) pypi packages, (c) SETI imports.

I did not apply pylint recommendations concerning purely style changes.  I created enough reviewer work.

### CODE REVIEW

**Comment by texadactyl** [comment]
I decided to leave the Dockerfile as-is because (a) it should rely on pypi for a functional  blimpy and (b) @telegraphic pushed blimpy master branch to pypi.

**Comment by texadactyl** [comment]
Ran my usual testing paradigm each time after updating fork and, implicitly, the PR (step-wise refinement):
* Download patch-1.  Unzip. cd into patch-1.
* pip3 uninstall turbo_seti
* python3 setup.py install
* cd test; python3 download_test_data.py; cd ..
* pytest
* Run turboSETI twice: with -p unspecified and with -p 2.

**Comment by telegraphic** [comment]
Merging -- apologies for the ugly merge with a `HEAD >>> ` left in

**Comment by texadactyl** [comment]
Actually, it was pretty funny!   (:   My strange sense of humour, I guess.

**Pull request merged**
