### PR TITLE
Parallelize workloads on the GPU with CUDA.

### PR DESCRIPTION
**Pull request by luigifcruz**
This pull-request adds a GPU-mode option with performance gains ranging from 6.8x to 20.0x depending on hardware and file compression. This branch proposes the following changes to `turbo_seti`:
- Parallelized workloads on the GPU with CuPy (with CPU-only mode).
- A vectorized de-doppler algorithm based on the current one (Taylor Tree).
- Added single-precision `float32` support.
- Replaced Cython with Numba (same performance, with JIT compilation and less code)
- Added profiling options to the client.
- Custom CUDA kernel for `hitsearch`.

#### Environment
```bash
turboSETI Voyager1.single_coarse.fine_res.h5 # CPU-mode
turboSETI Voyager1.single_coarse.fine_res.h5 -g y # GPU-mode
```
#### Float Precision
```bash
turboSETI Voyager1.single_coarse.fine_res.h5 # Double-Precision (float64)
turboSETI Voyager1.single_coarse.fine_res.h5 -S y # Single-Precision (float32)
```
#### Profiling
```bash
turboSETI Voyager1.single_coarse.fine_res.h5 -P y
```

#### Double-Precision `float64`
| Version | Device | [Voyager 1](https://raw.githubusercontent.com/UCBerkeleySETI/turbo_seti/dev/test/Voyager1.single_coarse.fine_res.h5) | [Voyager 1 (2-bit)](http://blpd0.ssl.berkeley.edu/voyager_2bit/blc3_2bit_guppi_57386_VOYAGER1_0002.gpuspec.0000.fil) | [Voyager 1 (8-bit)](http://blpd0.ssl.berkeley.edu/voyager_8bit/blc07_guppi_57650_67573_Voyager1_0002.gpuspec.0000.fil) | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| `turbo_seti` | CPU | 0.44 minutes | 25.26 minutes | 23.06 minutes |
| `sonic_seti` | CPU | 0.36 minutes | 20.67 minutes | 22.44 minutes |
| `sonic_seti` | GPU | **0.05 minutes** | **2.73 minutes**   | **3.40 minutes**   |
|                       |          |  **_8.8x_**              | **_9.3x_**                  | **_6.8x_**               |

#### Single-Precision `float32`
| Version | Device | [Voyager 1](https://raw.githubusercontent.com/UCBerkeleySETI/turbo_seti/dev/test/Voyager1.single_coarse.fine_res.h5) | [Voyager 1 (2-bit)](http://blpd0.ssl.berkeley.edu/voyager_2bit/blc3_2bit_guppi_57386_VOYAGER1_0002.gpuspec.0000.fil) | [Voyager 1 (8-bit)](http://blpd0.ssl.berkeley.edu/voyager_8bit/blc07_guppi_57650_67573_Voyager1_0002.gpuspec.0000.fil) | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| `sonic_seti` | CPU | 0.26 minutes  | 16.13 minutes | 16.15 minutes  |
| `sonic_seti` | GPU |  **0.03 minutes** | **1.52 minutes**   | **2.14 minutes**   |
|                       |          |  **_8.7x_**               | **_10.6x_**                | **_7.5x_**                  |

#### Double-Precision `float64`
| Version | Device | [Voyager 1](https://raw.githubusercontent.com/UCBerkeleySETI/turbo_seti/dev/test/Voyager1.single_coarse.fine_res.h5) | [Voyager 1 (2-bit)](http://blpd0.ssl.berkeley.edu/voyager_2bit/blc3_2bit_guppi_57386_VOYAGER1_0002.gpuspec.0000.fil) | [Voyager 1 (8-bit)](http://blpd0.ssl.berkeley.edu/voyager_8bit/blc07_guppi_57650_67573_Voyager1_0002.gpuspec.0000.fil) | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| `sonic_seti` | CPU | 0.52 minutes | 29.14 minutes | 31.50 minutes |
| `sonic_seti` | GPU | **0.05 minutes** | **2.52 minutes**   | **3.45 minutes**   |
|                       |          |  **_10.4x_**              | **_11.6x_**                  | **_9.10x_**               |

#### Single-Precision `float32`
| Version | Device | [Voyager 1](https://raw.githubusercontent.com/UCBerkeleySETI/turbo_seti/dev/test/Voyager1.single_coarse.fine_res.h5) | [Voyager 1 (2-bit)](http://blpd0.ssl.berkeley.edu/voyager_2bit/blc3_2bit_guppi_57386_VOYAGER1_0002.gpuspec.0000.fil) | [Voyager 1 (8-bit)](http://blpd0.ssl.berkeley.edu/voyager_8bit/blc07_guppi_57650_67573_Voyager1_0002.gpuspec.0000.fil) | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| `sonic_seti` | CPU | 0.38 minutes  | 22.13 minutes | 24.02 minutes  |
| `sonic_seti` | GPU |  **0.04 minutes** | **1.62 minutes**   | **2.44 minutes**   |
|                       |          |  **_9.05x_**               | **_13.7x_**                | **_9.8x_**                  |

### Benchmark (GCP N1-HIGHCPU-8 w/ NVIDIA Tesla V100)
_Heavily CPU bottlenecked..._

#### Double-Precision `float64`
| Version | Device | [Voyager 1](https://raw.githubusercontent.com/UCBerkeleySETI/turbo_seti/dev/test/Voyager1.single_coarse.fine_res.h5) | [Voyager 1 (2-bit)](http://blpd0.ssl.berkeley.edu/voyager_2bit/blc3_2bit_guppi_57386_VOYAGER1_0002.gpuspec.0000.fil) | [Voyager 1 (8-bit)](http://blpd0.ssl.berkeley.edu/voyager_8bit/blc07_guppi_57650_67573_Voyager1_0002.gpuspec.0000.fil) | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| `sonic_seti` | CPU | 0.52 minutes | 29.14 minutes | 31.50 minutes |
| `sonic_seti` | GPU | **0.06 minutes** | **1.46 minutes**   | **2.38 minutes**   |
|                       |          |  **_8.7x_**              | **_20.0x_**                  | **_13.2x_**               |

#### Single-Precision `float32`
| Version | Device | [Voyager 1](https://raw.githubusercontent.com/UCBerkeleySETI/turbo_seti/dev/test/Voyager1.single_coarse.fine_res.h5) | [Voyager 1 (2-bit)](http://blpd0.ssl.berkeley.edu/voyager_2bit/blc3_2bit_guppi_57386_VOYAGER1_0002.gpuspec.0000.fil) | [Voyager 1 (8-bit)](http://blpd0.ssl.berkeley.edu/voyager_8bit/blc07_guppi_57650_67573_Voyager1_0002.gpuspec.0000.fil) | 
| ------------- | ------------- | ------------- | ------------- | ------------- |
| `sonic_seti` | CPU | 0.38 minutes  | 22.13 minutes | 24.02 minutes  |
| `sonic_seti` | GPU |  **0.05 minutes** | **1.15 minutes**   | **2.09 minutes**   |
|                       |          |  **_7.6x_**               | **_19.2x_**                | **_11.5x_**                  |

### To-Do
- [x] Patch current tests for GPU-mode.
- [x] Write new tests for GPU-mode.
- [x] Write missing documentation.

### CODE REVIEW

**Comment by texadactyl** [comment]
@luigifcruz There is a chance that this PR might need some re-tooling due to needed error fixes to the main branch this morning (Texas USA time).  Hopefully, no impact.

**turbo_seti version 1.3.2**

Issue #102 - find_event.py concatenating nil tables
Issue #106 - find_doppler.py not using cythonized bitrev()
Issue #111 - download all required data and test issue #102 - test subdirectory only

**Comment by luigifcruz** [comment]
@texadactyl Thanks for warning about the changes. I fixed the conflicts. I just need to patch the tests before merging.

**Comment by texadactyl** [comment]
@luigifcruz

1. The requirements.txt file should include ```cupy``` or the requirements_gpu.txt file should also be used in setup.py to establish the value of the setup install_requires= keyword parameter.

2. This version of turbo_seti should not be merged into the main branch since it cannot be installed on any system that does not have NVIDIA hardware.  Specifically, folks who have Intel and AMD/Ratheon graphics cards cannot install luigifcruz/turbo_seti in its current state.  I tried!

Maybe, you should create a whole new repository with a new name?  cuda_seti?  If so, please rename the executables that are produced by setup.py to avoid confusion.

Other opinions? @stevecroft @telegraphic

**Comment by texadactyl** [comment]
This is what happened to me when I tried to install cupy on an Acer Aspire 5 A515-44-R2SA (AMD CPU & graphics):

```
pip install cupy
Collecting cupy
  Downloading cupy-8.0.0.tar.gz (5.8 MB)
     |████████████████████████████████| 5.8 MB 1.6 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3rhqv17z/cupy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3rhqv17z/cupy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zzlqzhvc
         cwd: /tmp/pip-install-3rhqv17z/cupy/
    Complete output (47 lines):
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'wheel_includes': [], 'wheel_metadata': None, 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False, 'use_hip': False}
    
    -------- Configuring Module: cuda --------
    /tmp/tmpyeckat5w/a.cpp:1:10: fatal error: cublas_v2.h: No such file or directory
        1 | #include <cublas_v2.h>
          |          ^~~~~~~~~~~~~
    compilation terminated.
    command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3rhqv17z/cupy/setup.py", line 126, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip-install-3rhqv17z/cupy/cupy_setup_build.py", line 754, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip-install-3rhqv17z/cupy/cupy_setup_build.py", line 511, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: ['/tmp/pip-install-3rhqv17z/cupy/install/../cupy/core/include/cupy/cub', '/tmp/pip-install-3rhqv17z/cupy/install/../cupy/core/include']
      Library directories: []
      nvcc command       : (not found)
    
    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : (none)
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
      ROCM_HOME       : (none)
    
    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs.cupy.dev/en/stable/install.html
    
    ************************************************************
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by stevecroft** [comment]
I think it would be good to have a single branch (so that we don't have multiple versions of the secondary scripts) but have the CUDA tree de-Doppler algorithm be the default if an NVIDIA card is present, but fall back to the CPU version if not. Having setup.py check for an NVIDIA GPU would be good.

**Comment by texadactyl** [comment]
@stevecroft 
I agree.  I can imagine how to do that on Linux and Unix but it would need different interrogation code on MacOS and Windows.

**Comment by luigifcruz** [comment]
@texadactyl Thanks for testing my branch. You don't need to install `cupy` if you system doesn't have a CUDA or ROCm capable GPU. Whether to use the GPU or not is determined at runtime by the command line option `-g`.

**Comment by texadactyl** [comment]
@luigifcruz 
DId you try ```pytest``` on a machine without NVIDIA?

```
platform linux -- Python 3.8.6, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
rootdir: /mnt/elkdata/linux-home-folder/seti_testing/turbo_seti_testing/turbo_seti-luigi
plugins: cov-2.10.1, xdist-2.1.0, forked-1.3.0
collected 1 item / 1 error

==================================== ERRORS ====================================
___________________ ERROR collecting test/test_turbo_seti.py ___________________
ImportError while importing test module '/mnt/elkdata/linux-home-folder/seti_testing/turbo_seti_testing/turbo_seti-luigi/test/test_turbo_seti.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_turbo_seti.py:27: in <module>
    (Kernels(True, 2)), (Kernels(False, 2)), # Double-Precision
/usr/local/lib/python3.8/dist-packages/turbo_seti-1.3.2-py3.8.egg/turbo_seti/find_doppler/kernels/__init__.py:11: in __init__
    self._load_base()
/usr/local/lib/python3.8/dist-packages/turbo_seti-1.3.2-py3.8.egg/turbo_seti/find_doppler/kernels/__init__.py:27: in _load_base
    self.xp = importlib.import_module("cupy")
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'cupy'
=========================== short test summary info ============================
ERROR test/test_turbo_seti.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.27s ===============================
```

**Comment by luigifcruz** [comment]
@texadactyl Yep, tests aren't ready yet. The next commit should fix this. In the mean time, the following command should work on a CPU environment:

```
turboSETI Voyager1.single_coarse.fine_res.h5
```

**Comment by texadactyl** [comment]
@luigifcruz Also, you need to add a parameter to the class FindDoppler class search() function because not everyone uses the ```turboSETI``` command line.  E.g.,
```
def run_turbo_seti(arg_partitions: int, arg_file: str, arg_dir: str):
    print("\nrun_turbo_seti: Calling FindDoppler({})".format(arg_file))
    rmtree(arg_dir, ignore_errors=True)
    mkdir(arg_dir)
    print("run_turbo_seti: Output directory: {}".format(arg_dir))
    fdop = FindDoppler(datafile=arg_file, max_drift=2, out_dir=arg_dir)
    count_coarse_chan = fdop.data_handle.data_list[0]['n_coarse_chan']
    print("run_turbo_seti: Num coarse channels: {}".format(count_coarse_chan))
    t0 = time.time()
    fdop.search(n_partitions=arg_partitions, progress_bar='n')
    et = time.time() - t0
    print("run_turbo_seti: search(n_partitions={}) elapsed time = {} seconds"
          .format(arg_partitions, et))

```

**Comment by texadactyl** [comment]
Fortunately for Intel and AMD users, calling search() as illustrated in the previous sample program did not crash and completed normally as usual.

**Comment by luigifcruz** [comment]
@texadactyl The `FindDoppler` will default to CPU operation. The GPU-mode can be enabled by calling `FindDoppler` with `gpu_backend=True`. This will ensure this branch is compatible with all previous code.

**Comment by texadactyl** [comment]
@luigifcruz  I do see it in __init__().  Thanks.  So, by default in either way, no NVIDIA.  Looks good to me.  

Now, you just need to figure out how to run test/test_turbo_seti.py and test/test_pipelines in both environments:
- No NVIDIA - run CPU only.
- NVIDIA - run both CPU and GPU.

**Comment by texadactyl** [comment]
@luigifcruz 
pytest works fine now on my non-NVIDIA laptop.

**Comment by luigifcruz** [comment]
@texadactyl Awesome! Thanks for testing. I just need to write the missing documentation. I'll ping you when it's ready.

**Comment by telegraphic** [comment]
Having a quick play now, but hit a snag: If number of time steps in the file is not a factor of 2 (e.g. 20 instead of 16), this error will raise:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/turbo_seti/find_doppler/seti_event.py", line 104, in exec
    progress_bar=args.flag_progress_bar)
  File "/opt/conda/lib/python3.7/site-packages/turbo_seti/find_doppler/find_doppler.py", line 130, in search
    search_coarse_channel(data_dict, self, filewriter=filewriter, logwriter=logwriter)
  File "/opt/conda/lib/python3.7/site-packages/turbo_seti/find_doppler/find_doppler.py", line 180, in search_coarse_channel
    spectra, drift_indices = data_obj.load_data()
  File "/opt/conda/lib/python3.7/site-packages/turbo_seti/find_doppler/data_handler.py", line 258, in load_data
    spectra = self.kernels.xp.append(spectra, self.kernels.xp.zeros((self.tsteps-spectra.shape[0],
AttributeError: module 'cupy' has no attribute 'append'
```

**Comment by texadactyl** [comment]
"number of time steps in the file is not a factor of 2 (e.g. 20 instead of 16)" is threw me.  Multiple of 2? 

Which dataset is this?

**Comment by telegraphic** [comment]
Yep, should have said power of 2, not factor -- the tree dedispersion algorithm only works for 2^N time steps (IIRC).

This was a Parkes dataset, from the UWL receiver.

**Comment by luigifcruz** [comment]
@telegraphic Nice catch! This should be easily fixable. I will commit a patch in a few hours. Do you have the download URL for this file?

**Comment by texadactyl** [comment]
@luigifcruz 
Try the attached xx.h5 inside the zip.  I generated 17 time cadences.
[xx.zip](https://github.com/UCBerkeleySETI/turbo_seti/files/5366480/xx.zip)

**Comment by texadactyl** [comment]
There was no Travis CI run.  I wonder why?
@luigifcruz ?
@telegraphic ?

**Comment by luigifcruz** [comment]
For some reason Travis CI is [running the tests](https://travis-ci.org/github/UCBerkeleySETI/turbo_seti/pull_requests) for this pull-request but isn't posting the results to GitHub.

**Comment by luigifcruz** [comment]
One test is failing according to Travis CI but I can't reproduce the error. I manually tested my branch in four different virtual machine (Manjaro, Linux Mint, Ubuntu 18.04, and Ubuntu 16.04) and everything works as intended, all tests are passing. It's unclear why it's failing only with Travis CI.

**Comment by texadactyl** [comment]
This is what I did:

- Downloaded the ZIP file from https://github.com/luigifcruz/turbo_seti
- Unizipped
- cd into the highest level turbo_seti directory
- pip uninstall -y turbo_seti
- python3 setup.py install
- cd test
- python3 download_test_data.py

The result was a number of error messages related to numba,  See attached log.
[download_test_data.py.log](https://github.com/UCBerkeleySETI/turbo_seti/files/5401881/download_test_data.py.log)

**Comment by texadactyl** [comment]
Moving on, I tried the following at the highest level driectory: pytest 2>&1 | tee pytest.log
test/test_turbo_seti.py is failing.
See attached log.

[pytest.log](https://github.com/UCBerkeleySETI/turbo_seti/files/5401958/pytest.log)

So, my observations coincide with the Travis CI run.

**Comment by texadactyl** [comment]
Note that test/test_pipelines worked fine.  It is not as complex as test/test_turbo_seti.py.  How were you testing?

**Comment by luigifcruz** [comment]
Thanks for testing @texadactyl! I reviewed the attached logs and all errors appear to be related to `blimpy/io/sigproc.py`. I followed the same steps but no errors were reported. Are you running a experimental version of Blimpy? Looks like some functions from Blimpy have `@jit` decorators:

```python
File "../../../../../../../usr/local/lib/python3.8/dist-packages/blimpy-2.0.1-py3.8.egg/blimpy/io/sigproc.py", line 262:
@jit
def to_sigproc_keyword(keyword, value=None):
```

It also looks like both tests that failed in Travis CI (`test_turbo_seti.py::test_dask`) passed in your tests!

**Comment by texadactyl** [comment]
Yes, I forgot to remove the experimental blimpy aInd was fooled by having the same symptoms as Travis CI.

**Comment by texadactyl** [comment]
My guess is that you need to look at the .travis.yml file.

**Comment by texadactyl** [comment]
find_event.py was just updated to fix issue #115.

**Comment by luigifcruz** [comment]
The coverage tests are down ~5% because Travis CI doesn't support GPU at this time. It might be a good idea to setup a GPU-enabled machine on Google Cloud or perhaps a self-hosted Jetson Nano with GitHub Actions to automatically validate the code. 

```
Name                                                                                                                                                     Stmts   Miss  Cover                                       
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------                                       
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/data_handler.py                        159     20    87%                                       
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/file_writers.py                         88     12    86%                                       
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/find_doppler.py                        198      9    95%                                       
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/helper_functions.py                     34      0   100%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/kernels/__init__.py                     45      7    84%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/kernels/_hitsearch/__init__.py          13      0   100%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/kernels/_taylor_tree/__init__.py         1      0   100%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/kernels/_taylor_tree/_core_cuda.py      31      0   100%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/merge_dats_logs.py                      63     18    71%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_doppler/seti_event.py                           58      7    88%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_event/find_event.py                            192     52    73%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_event/find_event_pipeline.py                    98     25    74%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_event/plot_event.py                            120      8    93%
/home/luigi/anaconda3/envs/turboSETI/lib/python3.8/site-packages/turbo_seti-1.3.3-py3.8.egg/turbo_seti/find_event/plot_event_pipeline.py                    46     13    72%
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                                                                                                                     1146    171    85%
```

**Comment by texadactyl** [comment]
@stevecroft @siemion @telegraphic @david-macmahon @gajjarv 

@luigifcruz put significant time and effort into this major performance enhancement to turbo_seti.  He is certainly entitled to have this PR resolved ASAP.  

As you all know, I am neither an employee nor a commissioned contractor to the SETI Institute.  Therefore, I would not be comfortable in merging this major enhancement to turbo_seti unilaterally.  

My opinion is to proceed.  It would be helpful if all of you voiced your opinion about this.  Please speak up.

Thank you.

**Review by texadactyl — APPROVED** [review]
I have reviewed the source code with the caveat that I cannot personally test the NVIDIA-specific cases.  In addition, I have tested the CPU mode against a variety of HDF5 files.  

It is a pity that we cannot yet as of this date run Travis CI with NVIDIA hardware.  This is a significant source of what that process views as decreased coverage.

**Pull request merged**
